# Generated by Django 4.0.6 on 2022-07-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postres',
            fields=[
                ('idPostres', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('tipo', models.CharField(default='null', max_length=50, verbose_name='Tipo')),
                ('amount_box', models.SmallIntegerField(default=0, verbose_name='Cantidad por paquete')),
                ('coste_fabri', models.FloatField(default=0.0, verbose_name='Coste de fabricación')),
                ('coste', models.FloatField(default=0.0, verbose_name='Valor final')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'postre',
                'verbose_name_plural': 'postres',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Torta',
            fields=[
                ('idtorta', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('tipo', models.CharField(default='null', max_length=50, verbose_name='Tipo')),
                ('form_torta', models.CharField(default='null', max_length=100, verbose_name='Forma')),
                ('weight', models.FloatField(default=0.0, verbose_name='Peso en Kilogramos')),
                ('coste_fabri', models.FloatField(default=0.0, verbose_name='Coste de fabricación')),
                ('coste', models.FloatField(default=0.0, verbose_name='Valor final')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'torta',
                'verbose_name_plural': 'tortas',
                'ordering': ['-created'],
            },
        ),
    ]
