# Generated by Django 4.0.6 on 2022-07-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postres',
            name='idPostres',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='torta',
            name='idtorta',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
