# Generated by Django 4.0.6 on 2022-07-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_postres_idpostres_alter_torta_idtorta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postres',
            name='idPostres',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='torta',
            name='idtorta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
