# Generated by Django 4.0.6 on 2022-08-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_torta_materials_torta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torta',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
