# Generated by Django 4.1 on 2022-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_alter_torta_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="postres",
            name="materials",
            field=models.TextField(default="null", verbose_name="Materiales"),
        ),
        migrations.AddField(
            model_name="postres",
            name="slug",
            field=models.SlugField(default="null", max_length=200),
        ),
    ]
